#!/usr/bin/env python3
"""Render bench/LEDGER.md (full per-run telemetry) AND bench/SCOREBOARD.md (per-axis model comparison)
from box/ledger.jsonl (written by the harness) + ledger_backfill.jsonl.
usage: ledger2md.py   (sync first: rsync root@i5.local:/ai/bench/ledger.jsonl box/)"""
import json
from pathlib import Path

HERE = Path(__file__).parent
SHORT = {"Ternary-Bonsai-2-27B-Abliterated-PQ2_0-MTP.gguf": "Bonsai-27B PQ2_0-MTP", "Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf": "Qwen3.6-35B-A3B IQ2_M",
         "Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-IQ3_M.gguf": "Gemma4-26B-A4B IQ3_M"}
AXES = [("math", "gsm8k"), ("code", "humaneval"), ("knowledge", "mmlu_pro")]
# Absolute per-axis floors for the "best config" pick. Eligible = every axis BOTH within 1 sigma of the best
# clean score on that axis AND >= its floor (1 sigma catches noise ties; the floor stops a statistically
# excusable but actually-bad config sneaking in). Winner = fastest eligible config. Tune here.
FLOOR = {"math": 90.0, "code": 85.0, "knowledge": 65.0}


def mmlu_trunc(r):
    """MMLU-Pro-specific truncation count (a GSM8K/HumanEval cut-off must NOT flag the knowledge column).
    Prefer the per-set field (qual.py writes it now); else recompute from the per-item results jsonl;
    else -1 = unknown, treated as 'possibly contaminated' since the run had some truncation."""
    mp = (r["quality"].get("sets") or {}).get("mmlu_pro") or {}
    if "truncated" in mp:
        return mp["truncated"]
    f = HERE / "qual" / "results" / f"{r['label']}.jsonl"
    if f.exists():
        rr = [json.loads(l) for l in f.open()]
        return sum(1 for x in rr if x.get("set") == "mmlu_pro" and x.get("finish") == "length")
    return -1 if r["quality"].get("truncated", 0) else 0


def scoreboard(recs):
    """Per-axis model comparison. Answers which model wins on math / code / knowledge / speed, so the
    comparison lives in tooling, not in prose in notes.md. A winner is marked only among CLEAN scores:
    an MMLU-Pro run with truncated answers (cut-offs score wrong) is a FLOOR, flagged `!`, never a winner."""
    qruns = [r for r in recs if r.get("kind") == "quality" and r.get("quality")]
    speed = [r for r in recs if r.get("kind") == "specbench" and r.get("prompts")]
    # tuned-best decode tok/s per model file (from specbench rows; lives under different labels than the quality run)
    best_decode = {}
    for r in speed:
        ds = [p.get("decode_tps") for p in r["prompts"] if p.get("decode_tps") is not None]
        if ds:
            best_decode[r["model"]] = max(best_decode.get(r["model"], 0), max(ds))
    # one quality row per label: latest by ts (reruns share a label with the old-cap run)
    latest = {}
    for r in qruns:
        if r["label"] not in latest or (r.get("ts") or "") > (latest[r["label"]].get("ts") or ""):
            latest[r["label"]] = r
    rows = []
    for r in latest.values():
        s = r["quality"]["sets"]
        dec = best_decode.get(r["model"])
        rows.append({"label": r["label"], "model": r["model"], "trunc": mmlu_trunc(r),
                     "math": s.get("gsm8k", {}).get("pct"), "code": s.get("humaneval", {}).get("pct"),
                     "knowledge": s.get("mmlu_pro", {}).get("pct"),
                     "se": {ax: s.get(k, {}).get("se_pct") for ax, k in AXES},
                     "speed": dec if dec is not None else r["quality"].get("mean_decode_tps"),
                     "speed_tag": "" if dec is not None else "~"})
    rows.sort(key=lambda r: r["model"])

    def win(axis):  # winner among clean scores (knowledge clean = zero MMLU-Pro truncation; -1 = unknown, excluded)
        clean = [r for r in rows if r[axis] is not None and (axis != "knowledge" or r["trunc"] == 0)]
        if not clean:
            return None, any(r[axis] is not None for r in rows)
        best = max(clean, key=lambda r: r[axis])
        allv = [r for r in rows if r[axis] is not None]
        dirty = axis == "knowledge" and max(allv, key=lambda r: r[axis]) is not best
        return best["label"], dirty
    wins = {ax: win(ax) for ax, _ in AXES}
    speed_win = max((r for r in rows if r["speed"] is not None), key=lambda r: r["speed"], default=None)

    o = ["# Model scoreboard", "", f"{len(rows)} model configs. Generated by `bench/ledger2md.py` from the ledger. Do not edit by hand.",
         "Axes: math=GSM8K, code=HumanEval, knowledge=MMLU-Pro (temp 0, thinking off); speed=best decode tok/s (tuned config, may differ from the quality run's).",
         "", "| model | config | math (GSM8K) | code (HumanEval) | knowledge (MMLU-Pro) | speed tok/s |", "|---|---|---|---|---|---|"]
    for r in rows:
        cells = []
        for ax, _ in AXES:
            v = r[ax]
            if v is None:
                cells.append("-"); continue
            mark = " ✅" if wins[ax][0] == r["label"] else ""
            flag = "!" if ax == "knowledge" and r["trunc"] != 0 else ""  # r['trunc'] is MMLU-Pro-specific; -1 = unknown
            cells.append(f"{v:.1f}{flag}{mark}")
        sp = "-" if r["speed"] is None else f"{r['speed_tag']}{r['speed']:.1f}" + (" ✅" if speed_win and r["label"] == speed_win["label"] else "")
        short = r["model"].replace(".gguf", "").replace("-Uncensored-HauhauCS-Aggressive", "").replace("-Uncensored-HauhauCS-Balanced", "")
        o.append(f"| {short} | `{r['label']}` | {cells[0]} | {cells[1]} | {cells[2]} | {sp} |")
    o += ["", "**Axis winners:** " + ", ".join(f"{ax}=" + (wins[ax][0] or "?") for ax, _ in AXES) + (f", speed={speed_win['label']}" if speed_win else "")]
    if any(r["trunc"] != 0 for r in rows):
        o += ["", "- `!` = this run's MMLU-Pro answers include cut-offs (score wrong => the pct is a FLOOR, not comparable); winner marked only among zero-truncation runs. `!` on an unknown count (old records) means truncation could not be attributed per-set."]
    if any(wins[ax][1] for ax, _ in AXES):
        o += ["", "- knowledge leader is contaminated by truncation; the true knowledge winner is unresolved until a clean (zero-truncation) re-run."]
    if any(r["speed_tag"] for r in rows):
        o += ["", "- `~` speed = the quality run's in-run mean decode tok/s (no specbench row for that model); not the tuned best."]

    # --- Best config: fastest that holds quality (1 sigma of best-clean AND >= absolute floor, all axes) ---
    best_clean = {}
    for ax, _ in AXES:
        cl = [r[ax] for r in rows if r[ax] is not None and (ax != "knowledge" or r["trunc"] == 0)]
        best_clean[ax] = max(cl) if cl else None

    def eligible(r):
        why = []
        for ax, _ in AXES:
            v = r[ax]
            if v is None:
                return False, [f"no {ax}"]
            if ax == "knowledge" and r["trunc"] != 0:
                return False, ["knowledge not clean (truncated)"]
            if v < FLOOR[ax]:
                why.append(f"{ax} {v:.1f}<{FLOOR[ax]:g} floor")
            bc = best_clean[ax]
            se = (r["se"] or {}).get(ax) or 0
            if bc is not None and v < bc - max(se, 0):  # more than 1 sigma below the best clean score
                why.append(f"{ax} {v:.1f} >1sigma below best {bc:.1f}")
        return (len(why) == 0), why

    elig = [r for r in rows if eligible(r)[0] and r["speed"] is not None]
    o += ["", "## Best config (fastest that holds quality)", "",
          f"Eligible = every axis within 1 sigma of the best clean score AND >= floor (math {FLOOR['math']:g}, code {FLOOR['code']:g}, knowledge {FLOOR['knowledge']:g}). Winner = fastest eligible.", ""]
    if elig:
        w = max(elig, key=lambda r: r["speed"])
        short = w["model"].replace(".gguf", "").replace("-Uncensored-HauhauCS-Aggressive", "").replace("-Uncensored-HauhauCS-Balanced", "")
        o.append(f"**WINNER: `{w['label']}` ({short}) at {w['speed_tag']}{w['speed']:.1f} tok/s** — GSM8K {w['math']:.1f}, HumanEval {w['code']:.1f}, MMLU-Pro {w['knowledge']:.1f}.")
        o += ["", "| rank | config | speed tok/s | math | code | knowledge |", "|---|---|---|---|---|---|"]
        for i, r in enumerate(sorted(elig, key=lambda r: -r["speed"]), 1):
            o.append(f"| {i} | `{r['label']}` | {r['speed_tag']}{r['speed']:.1f} | {r['math']:.1f} | {r['code']:.1f} | {r['knowledge']:.1f} |")
        excl = [r for r in rows if not eligible(r)[0] and r["knowledge"] is not None]
        if excl:
            o += ["", "Excluded: " + "; ".join(f"`{r['label']}` (" + ", ".join(eligible(r)[1]) + ")" for r in excl)]
    else:
        o.append("No config is eligible yet — every candidate is excluded (usually MMLU-Pro not clean; see truncation flags). Resolve with the cap-2048 reruns.")
    return "\n".join(o) + "\n"


def builds_md(recs):
    """Registry of every distinct build seen in the ledger, so 'the optimal build' is a rebuildable artifact,
    not a path on one box. A build's identity = (source dir, full commit, cmake flags, dirty-diff sha). For each,
    print exactly how to recreate it and which run labels used it. Any dirty build lists its diff blob."""
    runs = [r for r in recs if r.get("kind") in ("specbench", "quality") and r.get("git")]
    builds = {}
    for r in runs:
        g = r["git"]
        src = (r.get("build") or "").rsplit("/", 1)[0]
        key = (src, g.get("commit_full") or g.get("commit"), json.dumps(g.get("cmake"), sort_keys=True), g.get("dirty_diff_sha"))
        b = builds.setdefault(key, {"g": g, "src": src, "build": r.get("build"), "labels": [], "ts": []})
        b["labels"].append(r["label"]); b["ts"].append(r.get("ts") or "")
    o = ["# Build registry", "", f"{len(builds)} distinct builds in the ledger. Generated by `bench/ledger2md.py`. Do not edit by hand.",
         "Each build is identified by source dir + full commit + cmake flags + dirty-diff sha. A row is recreatable by",
         "checking out the commit, applying the diff blob if any (`git apply builds/diffs/<sha>.diff` on the box), and",
         "building with the listed cmake flags. `dirty` builds without a diff sha are from before provenance hardening (2026-09-20) and are NOT fully recreatable.", ""]
    for b in sorted(builds.values(), key=lambda x: max(x["ts"]), reverse=True):
        g, cm = b["g"], (b["g"].get("cmake") or {})
        o.append(f"## `{b['build']}` @ {g.get('describe') or g.get('commit')}")
        o.append("")
        o.append(f"- source: `{b['src']}` branch `{g.get('branch')}` commit `{g.get('commit_full') or g.get('commit')}`")
        o.append(f"- cmake: CUDA arch {cm.get('cuda_arch')}, {cm.get('build_type')}, GGML_CUDA={cm.get('ggml_cuda')}, cxx `{cm.get('cxx')}`")
        tc = g.get("toolchain") or {}
        o.append(f"- toolchain: {tc.get('cxx')}; nvcc {tc.get('nvcc')}")
        if g.get("dirty"):
            ds = g.get("dirty_diff_sha")
            o.append(f"- **DIRTY** — " + (f"diff blob `builds/diffs/{ds}.diff` (recreate: checkout commit, `git apply` that diff)" if ds else "no diff captured (pre-hardening); NOT recreatable"))
            if g.get("untracked"):
                o.append(f"  - untracked files at build time: {', '.join(g['untracked'])}")
        n = len(b["labels"])
        shown = sorted(set(b["labels"]))
        o.append(f"- {n} runs ({len(shown)} labels): {', '.join('`' + l + '`' for l in shown[:20])}{' ...' if len(shown) > 20 else ''}")
        o.append("")
    return "\n".join(o) + "\n"


def load(p):
    return [json.loads(l) for l in p.open()] if p.exists() else []


def pair(rows, key, fmt="{:.2f}"):
    v = [r.get(key) for r in rows or []]
    return " / ".join(fmt.format(x) if x is not None else "-" for x in v) if v else "-"


def am(t, a, b, fmt="{:g}"):
    if not t or t.get(a) is None:
        return "-"
    return f"{fmt.format(t[a])} / {fmt.format(t[b])}" if t.get(b) is not None else fmt.format(t[a])


def main():
    recs = load(HERE / "ledger_backfill.jsonl") + load(HERE / "box" / "ledger.jsonl")
    runs = [r for r in recs if r.get("kind") in ("specbench", "quality")]
    runs.sort(key=lambda r: (SHORT.get(r["model"], r["model"]), r.get("ts") or "", r["label"]))
    out = ["# Run ledger", "", f"{len(recs)} records. Generated by `bench/ledger2md.py` from `bench/box/ledger.jsonl` (harness) + `bench/ledger_backfill.jsonl` (pre-ledger runs). Do not edit by hand.",
           "", "Pairs are code / reasoning prompt. avg / max where two numbers share a cell. Fixed: `-fa on -c 4096 -t 6 --load-mode none --jinja --parallel 1`, 200 tok, temp 0, thinking off.", ""]
    model = None
    for r in runs:
        m = SHORT.get(r["model"], r["model"])
        if m != model:
            model = m
            out += ["", f"## {m}", "",
                    "| time | label | commit | args (OFFLOAD) | decode tok/s | wall tok/s | prefill tok/s | accept | VRAM MiB | GPU % | power W | temp C | PCIe rx GB/s | PCIe tx GB/s | CPU % | DRAM rd GB/s | cache slots / hit % / MiB per step | quality | note |",
                    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        t, p, c, q = r.get("telemetry") or {}, r.get("prompts"), r.get("moe_cache"), r.get("quality")
        g = r.get("git") or {}
        cache = "-" if not c else f"{c.get('slots')} (a{c.get('admit')}) / {c.get('hit_rate_pct') if c.get('hit_rate_pct') is not None else '?'} / {c.get('upload_mib_per_step') if c.get('upload_mib_per_step') is not None else '?'}"
        qual = "-" if not q else "; ".join(f"{k} {v['pct']}±{v['se_pct']} (n={v['n']})" for k, v in q["sets"].items()) + f"; trunc {q['truncated']}, empty {q['empty']}, {q['mean_decode_tps']} tok/s"
        note = " ".join(x for x in (("FAILED: " + (r.get("error") or "no generation")) if not r.get("completed") else None, r.get("note"), f"env {r['env']}" if r.get("env") else None) if x)
        out.append("| " + " | ".join([
            (r.get("ts") or "?")[:16].replace("T", " "), f"`{r['label']}`" + (" (quality)" if r.get("kind") == "quality" else ""),
            f"{g.get('commit', '?')}{'+dirty' if g.get('dirty') else ''}", f"`{r.get('args', '')}` ({r.get('offload_min_batch') if r.get('offload_min_batch') is not None else '?'})",
            pair(p, "decode_tps"), pair(p, "wall_tps"), pair(p, "prefill_tps", "{:.1f}"), pair(p, "acceptance"),
            str(r.get("vram_mib") or "-"), am(t, "gpu_util_avg", "gpu_util_max", "{:.0f}"), am(t, "power_w_avg", "power_w_max", "{:.0f}"), am(t, "gpu_temp_c_max", None, "{:.0f}"),
            am(t, "pcie_rx_gbs_avg", "pcie_rx_gbs_max", "{:.2f}"), am(t, "pcie_tx_gbs_avg", "pcie_tx_gbs_max", "{:.2f}"), am(t, "cpu_busy_pct", None, "{:.0f}"),
            am(t, "dram_read_gbs_avg", "dram_read_gbs_max", "{:.1f}"), cache, qual, note.replace("|", "\\|")]) + " |")
    other = [r for r in recs if r.get("kind") not in ("specbench", "quality")]
    out += ["", "## llama-bench / one-off measurements", ""]
    for r in other:
        body = {k: v for k, v in r.items() if k.startswith("results")}
        out.append(f"- **`{r['label']}`** ({r.get('model')}, commit {r['git']['commit']}, `{r.get('args')}`, {r.get('build')}): `{json.dumps(body)}` — {r.get('note', '')}")
    (HERE / "LEDGER.md").write_text("\n".join(out) + "\n")
    (HERE / "SCOREBOARD.md").write_text(scoreboard(recs))
    (HERE / "BUILDS.md").write_text(builds_md(recs))
    print(f"LEDGER.md: {len(runs)} run rows, {len(other)} other records; SCOREBOARD.md + BUILDS.md written")


if __name__ == "__main__":
    main()
