#!/usr/bin/env python3
"""Render bench/LEDGER.md (full per-run telemetry) AND bench/SCOREBOARD.md (per-axis model comparison)
from box/ledger.jsonl (written by the harness) + ledger_backfill.jsonl.
usage: ledger2md.py   (sync first: rsync root@i5.local:/ai/bench/ledger.jsonl box/)"""
import json
from pathlib import Path

HERE = Path(__file__).parent
SHORT = {"Ternary-Bonsai-2-27B-Abliterated-PQ2_0-MTP.gguf": "Bonsai-27B PQ2_0-MTP", "Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf": "Qwen3.6-35B-A3B IQ2_M",
         "Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-IQ3_M.gguf": "Gemma4-26B-A4B IQ3_M"}
AXES = [("math", "gsm8k"), ("code", "humaneval"), ("knowledge", "mmlu_pro")]


def scoreboard(recs):
    """Per-axis model comparison. Answers which model wins on math / code / knowledge / speed, so the
    comparison lives in tooling, not in prose in notes.md. A winner is marked only among CLEAN scores:
    an MMLU-Pro run with truncated answers (cut-offs score wrong) is a FLOOR, flagged `!`, never a winner."""
    qruns = [r for r in recs if r.get("kind") == "quality" and r.get("quality")]
    speed = [r for r in recs if r.get("kind") == "specbench" and r.get("prompts")]
    # tuned-best decode tok/s per model file (from specbench rows; lives under different labels than the quality run)
    best_decode = {}
    for r in speed:
        ds = [p.get("decode_tps") for p in r["prompts"] if p.get("decode_tps") is not None]
        if ds:
            best_decode[r["model"]] = max(best_decode.get(r["model"], 0), max(ds))
    # one quality row per label: latest by ts (reruns share a label with the old-cap run)
    latest = {}
    for r in qruns:
        if r["label"] not in latest or (r.get("ts") or "") > (latest[r["label"]].get("ts") or ""):
            latest[r["label"]] = r
    rows = []
    for r in latest.values():
        s = r["quality"]["sets"]
        dec = best_decode.get(r["model"])
        rows.append({"label": r["label"], "model": r["model"], "trunc": r["quality"].get("truncated", 0),
                     "math": s.get("gsm8k", {}).get("pct"), "code": s.get("humaneval", {}).get("pct"),
                     "knowledge": s.get("mmlu_pro", {}).get("pct"),
                     "speed": dec if dec is not None else r["quality"].get("mean_decode_tps"),
                     "speed_tag": "" if dec is not None else "~"})
    rows.sort(key=lambda r: r["model"])

    def win(axis):  # winner among clean scores (knowledge clean = zero truncation); flag if the raw leader is dirty
        clean = [r for r in rows if r[axis] is not None and (axis != "knowledge" or r["trunc"] == 0)]
        if not clean:
            return None, any(r[axis] is not None for r in rows)
        best = max(clean, key=lambda r: r[axis])
        allv = [r for r in rows if r[axis] is not None]
        dirty = axis == "knowledge" and max(allv, key=lambda r: r[axis]) is not best
        return best["label"], dirty
    wins = {ax: win(ax) for ax, _ in AXES}
    speed_win = max((r for r in rows if r["speed"] is not None), key=lambda r: r["speed"], default=None)

    o = ["# Model scoreboard", "", f"{len(rows)} model configs. Generated by `bench/ledger2md.py` from the ledger. Do not edit by hand.",
         "Axes: math=GSM8K, code=HumanEval, knowledge=MMLU-Pro (temp 0, thinking off); speed=best decode tok/s (tuned config, may differ from the quality run's).",
         "", "| model | config | math (GSM8K) | code (HumanEval) | knowledge (MMLU-Pro) | speed tok/s |", "|---|---|---|---|---|---|"]
    for r in rows:
        cells = []
        for ax, _ in AXES:
            v = r[ax]
            if v is None:
                cells.append("-"); continue
            mark = " ✅" if wins[ax][0] == r["label"] else ""
            cells.append(f"{v:.1f}{'!' if ax == 'knowledge' and r['trunc'] else ''}{mark}")
        sp = "-" if r["speed"] is None else f"{r['speed_tag']}{r['speed']:.1f}" + (" ✅" if speed_win and r["label"] == speed_win["label"] else "")
        short = r["model"].replace(".gguf", "").replace("-Uncensored-HauhauCS-Aggressive", "").replace("-Uncensored-HauhauCS-Balanced", "")
        o.append(f"| {short} | `{r['label']}` | {cells[0]} | {cells[1]} | {cells[2]} | {sp} |")
    o += ["", "**Axis winners:** " + ", ".join(f"{ax}=" + (wins[ax][0] or "?") for ax, _ in AXES) + (f", speed={speed_win['label']}" if speed_win else "")]
    if any(r["trunc"] for r in rows):
        o += ["", "- `!` = MMLU-Pro run had truncated answers (cut-offs score wrong => that pct is a FLOOR, not comparable); winner marked only among zero-truncation runs."]
    if any(wins[ax][1] for ax, _ in AXES):
        o += ["", "- knowledge leader is contaminated by truncation; the true knowledge winner is unresolved until a clean (zero-truncation) re-run."]
    if any(r["speed_tag"] for r in rows):
        o += ["", "- `~` speed = the quality run's in-run mean decode tok/s (no specbench row for that model); not the tuned best."]
    return "\n".join(o) + "\n"


def load(p):
    return [json.loads(l) for l in p.open()] if p.exists() else []


def pair(rows, key, fmt="{:.2f}"):
    v = [r.get(key) for r in rows or []]
    return " / ".join(fmt.format(x) if x is not None else "-" for x in v) if v else "-"


def am(t, a, b, fmt="{:g}"):
    if not t or t.get(a) is None:
        return "-"
    return f"{fmt.format(t[a])} / {fmt.format(t[b])}" if t.get(b) is not None else fmt.format(t[a])


def main():
    recs = load(HERE / "ledger_backfill.jsonl") + load(HERE / "box" / "ledger.jsonl")
    runs = [r for r in recs if r.get("kind") in ("specbench", "quality")]
    runs.sort(key=lambda r: (SHORT.get(r["model"], r["model"]), r.get("ts") or "", r["label"]))
    out = ["# Run ledger", "", f"{len(recs)} records. Generated by `bench/ledger2md.py` from `bench/box/ledger.jsonl` (harness) + `bench/ledger_backfill.jsonl` (pre-ledger runs). Do not edit by hand.",
           "", "Pairs are code / reasoning prompt. avg / max where two numbers share a cell. Fixed: `-fa on -c 4096 -t 6 --load-mode none --jinja --parallel 1`, 200 tok, temp 0, thinking off.", ""]
    model = None
    for r in runs:
        m = SHORT.get(r["model"], r["model"])
        if m != model:
            model = m
            out += ["", f"## {m}", "",
                    "| time | label | commit | args (OFFLOAD) | decode tok/s | wall tok/s | prefill tok/s | accept | VRAM MiB | GPU % | power W | temp C | PCIe rx GB/s | PCIe tx GB/s | CPU % | DRAM rd GB/s | cache slots / hit % / MiB per step | quality | note |",
                    "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        t, p, c, q = r.get("telemetry") or {}, r.get("prompts"), r.get("moe_cache"), r.get("quality")
        g = r.get("git") or {}
        cache = "-" if not c else f"{c.get('slots')} (a{c.get('admit')}) / {c.get('hit_rate_pct') if c.get('hit_rate_pct') is not None else '?'} / {c.get('upload_mib_per_step') if c.get('upload_mib_per_step') is not None else '?'}"
        qual = "-" if not q else "; ".join(f"{k} {v['pct']}±{v['se_pct']} (n={v['n']})" for k, v in q["sets"].items()) + f"; trunc {q['truncated']}, empty {q['empty']}, {q['mean_decode_tps']} tok/s"
        note = " ".join(x for x in (("FAILED: " + (r.get("error") or "no generation")) if not r.get("completed") else None, r.get("note"), f"env {r['env']}" if r.get("env") else None) if x)
        out.append("| " + " | ".join([
            (r.get("ts") or "?")[:16].replace("T", " "), f"`{r['label']}`" + (" (quality)" if r.get("kind") == "quality" else ""),
            f"{g.get('commit', '?')}{'+dirty' if g.get('dirty') else ''}", f"`{r.get('args', '')}` ({r.get('offload_min_batch') if r.get('offload_min_batch') is not None else '?'})",
            pair(p, "decode_tps"), pair(p, "wall_tps"), pair(p, "prefill_tps", "{:.1f}"), pair(p, "acceptance"),
            str(r.get("vram_mib") or "-"), am(t, "gpu_util_avg", "gpu_util_max", "{:.0f}"), am(t, "power_w_avg", "power_w_max", "{:.0f}"), am(t, "gpu_temp_c_max", None, "{:.0f}"),
            am(t, "pcie_rx_gbs_avg", "pcie_rx_gbs_max", "{:.2f}"), am(t, "pcie_tx_gbs_avg", "pcie_tx_gbs_max", "{:.2f}"), am(t, "cpu_busy_pct", None, "{:.0f}"),
            am(t, "dram_read_gbs_avg", "dram_read_gbs_max", "{:.1f}"), cache, qual, note.replace("|", "\\|")]) + " |")
    other = [r for r in recs if r.get("kind") not in ("specbench", "quality")]
    out += ["", "## llama-bench / one-off measurements", ""]
    for r in other:
        body = {k: v for k, v in r.items() if k.startswith("results")}
        out.append(f"- **`{r['label']}`** ({r.get('model')}, commit {r['git']['commit']}, `{r.get('args')}`, {r.get('build')}): `{json.dumps(body)}` — {r.get('note', '')}")
    (HERE / "LEDGER.md").write_text("\n".join(out) + "\n")
    (HERE / "SCOREBOARD.md").write_text(scoreboard(recs))
    print(f"LEDGER.md: {len(runs)} run rows, {len(other)} other records; SCOREBOARD.md written")


if __name__ == "__main__":
    main()
